export default {
  notification: {
    CHANGE_NOTIFICATION_INPUT: 'CHANGE_NOTIFICATION_INPUT',
    REMOVE_PHOTO: 'REMOVE_PHOTO',
    ADD_PHOTO: 'ADD_PHOTO',
    ADD_NOTIFICATION_INFO: 'ADD_NOTIFICATION_INFO',
  },

  router: {
    NOTIFICATION_EDIT: 'NOTIFICATION_EDIT',
  },

  common: {
    NOTIFICATION_SAVE: 'NOTIFICATION_SAVE',
    RETURN_BACK: 'RETURN_BACK',
  },

}