export default {
  notification: {
    CHANGE_NOTIFICATION_INPUT: 'CHANGE_NOTIFICATION_INPUT',
    REMOVE_PHOTO: 'REMOVE_PHOTO',
    ADD_PHOTO: 'ADD_PHOTO',
    ADD_NOTIFICATION_INFO: 'ADD_NOTIFICATION_INFO',
  },

  notifications: {
    NOTIFICATION_ADD: 'NOTIFICATION_ADD',
    NOTIFICATION_EDIT_EXISTED: 'NOTIFICATION_EDIT_EXISTED',
  },

  router: {
    NOTIFICATION_EDIT: 'NOTIFICATION_EDIT',
  },

  common: {
    RETURN_BACK: 'RETURN_BACK',
  },

}